### ISSUE TITLE
Does no longer show "Indexes" for h2databases greater then version 2.0

### ISSUE THREAD

**Issue by keinhaar** [squirrel-sql-client/squirrel-sql-code#11]
after switching to h2 database driver 2.0.206 the tab "Indexes" is just empty.
The Indexes are shown in the tree view, but only the Inof Tab is filled. No Details, no Source.

**Comment by gerdwagner** [comment]
Fixed and committed to our GIT repository. Will be available in future snapshots and versions.

Excerpt from change log:
H2 DB versions greater than 2.* didn't show indexes in the Object tree's index details tab.
  The reason was that H2 changed the table type of ordinary tables from "TABLE" from to "BASE TABLE".

**Comment by keinhaar** [comment]
@gerdwagner 
I tried the latest snapshot.
Sorry, this does not fix the issue for me. The index is shown in the tree, but the "Deatils" and the "Source" Tab are still empty. Also when selecting the Table in the tree, the "Indexes" Tab is still empty.

**Comment by gerdwagner** [comment]
> The index is shown in the tree, but the "Deatils" and the "Source" Tab are still empty.
This concerns the H2 Plugin. In H2 version 2.* the  information schema tables were restructured. I think I was able to fix the Plugins access to these tables.

> Also when selecting the Table in the tree, the "Indexes" Tab is still empty.
Sorry for the inconvenience. Please give the next snapshot a try.

**Comment by keinhaar** [comment]
Just tried the snapshot from your last comment.
Works well now. 
Thanks for your work!
